spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wishlistdb
    username: admin
    password: securepassword
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080