# Database
POSTGRESQL_USERNAME: admin
POSTGRESQL_PASSWORD: securepassword
POSTGRESQL_HOST:
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: wishlistdb

# Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

# Email Config
EMAIL_HOST:
EMAIL_PORT:
EMAIL_ID:
EMAIL_PASSWORD:
VERIFY_EMAIL_HOST: http://localhost:8085